# Generated by Django 5.1.3 on 2025-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationresult',
            name='request_hex',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attestationresult',
            name='voting_round_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
