# Generated by Django 5.2.12 on 2026-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdc', '0002_alter_attestationresult_request_hex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationresult',
            name='request_hex',
            field=models.CharField(),
        ),
        migrations.AddIndex(
            model_name='attestationresult',
            index=models.Index(fields=['request_hex', '-voting_round_id'], name='fdc_attestation_req_round_idx'),
        ),
    ]
