# templates
 
.test_template: &test
  stage: test
  variables:
    GIT_STRATEGY: none
    CONFIG_MODULE: coston
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
    entrypoint: [""]
  only:
    - branches

.build_template: &build
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "$CI_COMMIT_SHA" > COMMIT_HASH
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json


stages:
  - build
  - test

build_branches:
  <<: *build
  script:
    - /kaniko/executor 
      --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/Dockerfile 
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH 
      --cache=true 
      --cache-ttl=120h
  only:
    - branches

build_tags:
  <<: *build
  script:
    - /kaniko/executor 
      --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/docker/remote/Dockerfile 
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG 
      --cache=true 
      --cache-ttl=120h
  only:
    - tags

test_ruff:
  <<: *test
  script:
    - cd /app
    - pip install -r dev-requirements.txt
    - python -m ruff check .
    - python -m ruff format --check

test_django:
  <<: *test
  script:
    - cd /app
    - pip install -r dev-requirements.txt
    - coverage run --source="." manage.py test --settings=project.settings.ci_testing
    - coverage xml
    - mv coverage.xml $CI_PROJECT_DIR/
    - mv testreport.xml $CI_PROJECT_DIR/
  artifacts:
    reports:
      junit: testreport.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
