# Generated by Django 5.1.3 on 2025-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftso', '0002_alter_feedresult_voting_round_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomresult',
            name='voting_round_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
