# Generated by Django 5.2.12 on 2026-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftso', '0003_alter_randomresult_voting_round_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedresult',
            name='voting_round_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddIndex(
            model_name='feedresult',
            index=models.Index(fields=['voting_round_id', 'feed_id'], name='ftso_feed_round_feedid_idx'),
        ),
    ]
