# Generated by Django 5.2.12 on 2026-08-25 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('message_class', models.CharField(choices=[('ftso_round', 'FTSO round payload'), ('fdc_round', 'FDC round payload'), ('tee_action_result', 'TEE action result'), ('proposal', 'Proposal package')], max_length=32)),
                ('raw', models.BinaryField()),
                ('origin', models.CharField(max_length=128)),
                ('gated_at', models.DateTimeField()),
                ('size_bytes', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
            },
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('message_class', models.CharField(choices=[('ftso_round', 'FTSO round payload'), ('fdc_round', 'FDC round payload'), ('tee_action_result', 'TEE action result'), ('proposal', 'Proposal package')], max_length=32)),
                ('trigger_ref', models.CharField(db_index=True, max_length=128)),
                ('origin', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('open', 'Open'), ('met', 'Met'), ('unmet', 'Unmet'), ('refused', 'Refused')], default='open', max_length=16)),
                ('first_seen_at', models.DateTimeField()),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Expectation',
                'verbose_name_plural': 'Expectations',
                'indexes': [models.Index(fields=['state', 'last_attempt_at'], name='dal_expecta_state_04596d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArtifactIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_key', models.CharField(db_index=True, max_length=64)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_entries', to='dal.artifact')),
            ],
            options={
                'verbose_name': 'Artifact index entry',
                'verbose_name_plural': 'Artifact index entries',
                'constraints': [models.UniqueConstraint(fields=('index_key', 'artifact'), name='dal_index_entry_unique')],
            },
        ),
    ]
