# Generated by Django 5.2.12 on 2026-08-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectation',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
