"""The signing scheme, checked against vectors generated by the Go producer.

The vectors in ``vectors.json`` were emitted by go-flare-common's own signing
package and tee-node's own ``ActionResult.Hash``. That is the point of them: a
Python implementation checked only against Python would agree with its own
misreading of the scheme, and a wrong sighash does not fail loudly -- it
produces a signature that verifies against nothing.
"""

import json
from pathlib import Path

import pytest

from dal.gate.signing import (
    CSP_PROPOSAL,
    PROXY_ACTION_RESULT,
    TEE_ACTION_RESULT,
    TEE_VOTE_HASH,
    SignatureError,
    action_result_hash,
    payload_hash,
    recover,
    verify,
)

VECTORS = json.loads((Path(__file__).parent / "vectors.json").read_text())
BY_NAME = {v["name"]: v for v in VECTORS}

PREFIXES = {
    "tee_action_result": TEE_ACTION_RESULT,
    "proxy_action_result": PROXY_ACTION_RESULT,
    "tee_vote_hash": TEE_VOTE_HASH,
    "csp_proposal": CSP_PROPOSAL,
}


def unhex(s: str) -> bytes:
    return bytes.fromhex(s.removeprefix("0x"))


@pytest.mark.parametrize("vector", VECTORS, ids=lambda v: v["name"])
def test_prefix_matches_go(vector):
    assert PREFIXES[vector["name"]] == unhex(vector["prefix"])


@pytest.mark.parametrize("vector", VECTORS, ids=lambda v: v["name"])
def test_payload_hash_matches_go(vector):
    assert payload_hash(
        PREFIXES[vector["name"]], vector["chainId"], unhex(vector["dataHash"])
    ) == unhex(vector["signHash"])


@pytest.mark.parametrize("vector", VECTORS, ids=lambda v: v["name"])
def test_recovers_to_the_go_signer(vector):
    assert (
        recover(unhex(vector["signHash"]), unhex(vector["signature"]))
        == vector["signer"]
    )
    verify(unhex(vector["signHash"]), unhex(vector["signature"]), vector["signer"])


@pytest.mark.parametrize("name", ["tee_action_result", "proxy_action_result"], ids=str)
def test_action_result_hash_matches_go(name):
    v = BY_NAME[name]
    assert action_result_hash(
        unhex(v["data"]), unhex(v["actionId"]), v["submissionTag"], v["status"]
    ) == unhex(v["dataHash"])


def test_the_two_action_result_signatures_share_a_data_hash():
    # One result, two signers, two prefixes -- so the SAME dataHash must produce
    # two different sign hashes. If domain separation were dropped, a machine's
    # signature would be accepted as its proxy's.
    tee, proxy = BY_NAME["tee_action_result"], BY_NAME["proxy_action_result"]
    assert tee["dataHash"] == proxy["dataHash"]
    assert tee["signHash"] != proxy["signHash"]


def test_a_prefix_is_not_replayable_across_classes():
    v = BY_NAME["tee_action_result"]
    other = payload_hash(PROXY_ACTION_RESULT, v["chainId"], unhex(v["dataHash"]))
    with pytest.raises(SignatureError):
        verify(other, unhex(v["signature"]), v["signer"])


def test_a_signature_is_not_replayable_across_chains():
    v = BY_NAME["tee_action_result"]
    elsewhere = payload_hash(TEE_ACTION_RESULT, v["chainId"] + 1, unhex(v["dataHash"]))
    with pytest.raises(SignatureError):
        verify(elsewhere, unhex(v["signature"]), v["signer"])


def test_status_is_part_of_the_hash():
    v = BY_NAME["tee_action_result"]
    flipped = action_result_hash(
        unhex(v["data"]), unhex(v["actionId"]), v["submissionTag"], v["status"] + 1
    )
    assert flipped != unhex(v["dataHash"])


def test_submission_tag_is_part_of_the_hash():
    # The same result under a different tag must not reuse a signature: the
    # `threshold` and `end` answers to one instruction are different artifacts.
    v = BY_NAME["tee_action_result"]
    assert action_result_hash(
        unhex(v["data"]), unhex(v["actionId"]), "end", v["status"]
    ) != unhex(v["dataHash"])


def test_high_s_is_refused():
    v = BY_NAME["tee_action_result"]
    sig = bytearray(unhex(v["signature"]))
    n = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
    s = int.from_bytes(sig[32:64], "big")
    sig[32:64] = (n - s).to_bytes(32, "big")
    sig[64] ^= 1  # the flipped-s counterpart uses the other recovery id
    with pytest.raises(SignatureError, match="canonical"):
        recover(unhex(v["signHash"]), bytes(sig))


@pytest.mark.parametrize("length", [0, 64, 66], ids=str)
def test_wrong_length_is_refused(length):
    with pytest.raises(SignatureError, match="65 bytes"):
        recover(unhex(BY_NAME["csp_proposal"]["signHash"]), b"\x01" * length)


def test_zero_r_is_refused():
    v = BY_NAME["csp_proposal"]
    sig = b"\x00" * 32 + unhex(v["signature"])[32:]
    with pytest.raises(SignatureError, match="r is out of range"):
        recover(unhex(v["signHash"]), sig)


def test_a_tampered_signature_does_not_recover_to_the_signer():
    v = BY_NAME["csp_proposal"]
    sig = bytearray(unhex(v["signature"]))
    sig[0] ^= 0xFF
    with pytest.raises(SignatureError):
        verify(unhex(v["signHash"]), bytes(sig), v["signer"])
